# Generated by Django 6.1.1 on 2026-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
